# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: A2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x41\x32.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"j\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07version\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\'\n\x0bReplicaInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\".\n\x0cReplicasList\x12\x1e\n\x08replicas\x18\x01 \x03(\x0b\x32\x0c.ReplicaInfo\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x0cWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"Z\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12+\n\x07version\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xcb\x01\n\x0eRegisterServer\x12\x30\n\x15GetReadQuorumReplicas\x12\x06.Empty\x1a\r.ReplicasList\"\x00\x12&\n\x0bGetReplicas\x12\x06.Empty\x1a\r.ReplicasList\"\x00\x12\x31\n\x16GetWriteQuorumReplicas\x12\x06.Empty\x1a\r.ReplicasList\"\x00\x12,\n\x0fRegisterReplica\x12\x0c.ReplicaInfo\x1a\t.Response\"\x00\x32\xaf\x01\n\x07Replica\x12&\n\tShareInfo\x12\x0c.ReplicaInfo\x1a\t.Response\"\x00\x12%\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\"\x00\x12(\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\"\x00\x12+\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'A2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=45
  _EMPTY._serialized_end=52
  _DELETEREQUEST._serialized_start=54
  _DELETEREQUEST._serialized_end=83
  _DELETERESPONSE._serialized_start=85
  _DELETERESPONSE._serialized_end=117
  _READREQUEST._serialized_start=119
  _READREQUEST._serialized_end=146
  _READRESPONSE._serialized_start=148
  _READRESPONSE._serialized_end=254
  _REPLICAINFO._serialized_start=256
  _REPLICAINFO._serialized_end=295
  _REPLICASLIST._serialized_start=297
  _REPLICASLIST._serialized_end=343
  _RESPONSE._serialized_start=345
  _RESPONSE._serialized_end=371
  _WRITEREQUEST._serialized_start=373
  _WRITEREQUEST._serialized_end=432
  _WRITERESPONSE._serialized_start=434
  _WRITERESPONSE._serialized_end=524
  _REGISTERSERVER._serialized_start=527
  _REGISTERSERVER._serialized_end=730
  _REPLICA._serialized_start=733
  _REPLICA._serialized_end=908
# @@protoc_insertion_point(module_scope)
